#!/bin/bash
# -o nounset because some values are magically set by docker cloud build
set -o errexit -o pipefail

# Don't use docker cloud build's IMAGE_NAME, because it already contains the tag latest.
IMAGE_NAME=schnatterer/letsencrypt-tomcat

function main() {
    # TODO implement logic that for tagged builds that pass the tag version down to these images as build-arg
    
    docker build -t schnatterer/letsencrypt-tomcat .
    docker push schnatterer/letsencrypt-tomcat
    
    docker build -t schnatterer/letsencrypt-tomcat:standalone  --file=examples/standalone/Dockerfile .
    docker push schnatterer/letsencrypt-tomcat:standalone
    
    docker build -t schnatterer/letsencrypt-tomcat:spring-boot  --file=examples/spring-boot/Dockerfile .
    docker push schnatterer/letsencrypt-tomcat:spring-boot

    docker build -t schnatterer/letsencrypt-tomcat:embedded-tomcat  --file=examples/embedded-tomcat/Dockerfile .
    docker push schnatterer/letsencrypt-tomcat:embedded-tomcat
}

main "$@"