#!/bin/bash
# -o nounset because some values are magically set by docker cloud build
set -o errexit -o pipefail

# Don't use docker cloud build's IMAGE_NAME, because it already contains the tag latest.
IMAGE_NAME=schnatterer/letsencrypt-tomcat
DOCKER_TAG="latest"
# Don't repeat "latest" in examples, e.g. :standalone instead of latest-standalone
DOCKER_TAG_EXAMPLES=""

POTENTIAL_TAG=$(git tag --points-at HEAD)
if [[ -n "${POTENTIAL_TAG}" ]]; then
    DOCKER_TAG="${POTENTIAL_TAG}"
    DOCKER_TAG_EXAMPLES="${POTENTIAL_TAG}-"
fi

function main() {
    
    docker build --tag schnatterer/letsencrypt-tomcat:${DOCKER_TAG} .
    push schnatterer/letsencrypt-tomcat:${DOCKER_TAG}
    
    docker build --tag schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}standalone \
        --file=examples/standalone/Dockerfile \
        --build-arg=LETSENCRYPT_TOMCAT_VERSION=${DOCKER_TAG} \
        .
    push schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}standalone
    
    docker build --tag schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}spring-boot \
         --file=examples/spring-boot/Dockerfile \
         --build-arg=LETSENCRYPT_TOMCAT_VERSION=${DOCKER_TAG} \
         .
    push schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}spring-boot

    docker build --tag schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}embedded-tomcat \
        --file=examples/embedded-tomcat/Dockerfile \
        --build-arg=LETSENCRYPT_TOMCAT_VERSION=${DOCKER_TAG} \
        .
    push schnatterer/letsencrypt-tomcat:${DOCKER_TAG_EXAMPLES}embedded-tomcat
}

function push() {
    if [ "${SKIP_PUSH}" = true ] ; then
        echo "Skipping push, because SKIP_PUSH set to true"
    else
        docker push "$1"
    fi
}

main "$@"
